### ISSUE TITLE
0.0.22 version does not work correctly

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/vscode#77]
The latest version of the extension, after bumping all dependencies, does not seem to work correctly.

Possible causes:

* https://github.com/erlang-ls/vscode/pull/70
* https://github.com/erlang-ls/vscode/pull/75

The pre-built version of the extension (not yet published) can be found as a zipped artifact at:

https://github.com/erlang-ls/vscode/runs/2106229605

The current behaviour is that, when an Erlang file is open, the language server is not even started. I will try to have a look, but if someone would like to help finding the issue you are welcome. In the worse case, I will have to roll back the dependencies bump.

FYI @maxno-kivra and @alanz

**Comment by robertoaloi** [comment]
When debugging the extension itself, everything works fine. This is only showing when using the packaged extension.

**Comment by robertoaloi** [comment]
This was caused by the bump of `vscode-languageclient` from `6.1.4` to `7.0.0`. Reverted for now, until we find the actual issue.

**Comment by maxno-kivra** [comment]
OK, sorry about that. I'll try to investigate a bit today and see if I can figure it out.

**Comment by maxno-kivra** [comment]
I just tested https://github.com/erlang-ls/vscode/commit/6cc1400fc845d92f659c8ede211d6c9d44029192, the commit before reverting vscode-languageclient, and opened our big Erlang project. The server started just fine, and go to definition and find references work.

I _do_ run `0.11.0+build.1470.reffab7423, OTP version: 23` though. Not sure if that has something to do with it. My config is:

```yaml
opt_path: "/Users/maxno/.asdf/installs/erlang/23.2.3"
plt_path: "_build/default/rebar3_23.2.3_plt"
code_path_extra_dirs:
  - "_build/default/lib/*/ebin"
deps_dirs:
  - "_build/default/lib/*"
  - "_build/test/lib/*"
  - "_build/doc/lib/*"
include_dirs:
  - "include"
  - "_build/default/lib"
  - "_build/default/lib/*/include"
lenses:
  disabled:
    - suggest-spec
```

Rebar3 version: `rebar 3.14.2 on Erlang/OTP 23 Erts 11.1.7`. Both Erlang/OTP and rebar3 are installed using `asdf`, again not sure if it matters.
